# -*- coding: utf-8 -*-
"""言い換え生成.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpURfN9xxU9ynijIpT_KzEzt20E15Kmi

# 事前にやること
1. ランタイムのタイプを "GPU" に変更
2. 設定ファイル "rnn.yaml" および "san.yaml" をアップロード
"""

from google.colab import drive
drive.mount('/content/drive')

# ライブラリのインストール

! pip install janome
! pip install OpenNMT-py

# 前処理（日本語の単語分割）

from janome.tokenizer import Tokenizer
tokenizer = Tokenizer()

# train
fout = open("ja.train.txt", "w")
fin = open("/content/drive/MyDrive/Vdata/transrate/ja.comp.train.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

fout = open("ja.simp.train.txt", "w")
fin = open("/content/drive/MyDrive/Vdata/transrate/ja.simp.train.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

# valid
fout = open("ja.valid.txt", "w")
fin = open("/content/drive/MyDrive/Vdata/transrate/ja.comp.valid.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

fout = open("ja.simp.valid.txt", "w")
fin = open("/content/drive/MyDrive/Vdata/transrate/ja.simp.valid.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

# eval
fout = open("ja.eval.txt", "w")
fin = open("/content/drive/MyDrive/Vdata/transrate/ja.comp.eval.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

# データセットの準備

! onmt_build_vocab -config "rnn.yaml" -n_sample 50000 -overwrite

# 訓練

! onmt_train -config "rnn.yaml"

# データセットの準備2

! onmt_build_vocab -config "rnn2.yaml" -n_sample 50000 -overwrite

# 訓練

! onmt_train -config "rnn2.yaml"

# 翻訳

! onmt_translate -model "rnn_step_14000.pt" "2-rnn_step_11000.pt" -src "ja.eval.txt" -output "miyata_pred.rnn.simp.txt" -gpu "0" -verbose